/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as PhoneRepairOrmskirkRouteImport } from './routes/phone-repair-ormskirk'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RepairsRouteImport } from './routes/repairs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SellRouteImport } from './routes/sell'
import { Route as SellYourPhoneRouteImport } from './routes/sell-your-phone'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnlockingRouteImport } from './routes/unlocking'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminBuyPhoneRouteImport } from './routes/_authenticated/admin.buy-phone'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminDayEndRouteImport } from './routes/_authenticated/admin.day-end'
import { Route as AuthenticatedAdminDirectSaleRouteImport } from './routes/_authenticated/admin.direct-sale'
import { Route as AuthenticatedAdminEnquiriesRouteImport } from './routes/_authenticated/admin.enquiries'
import { Route as AuthenticatedAdminInvoiceTermsRouteImport } from './routes/_authenticated/admin.invoice-terms'
import { Route as AuthenticatedAdminNewRepairRouteImport } from './routes/_authenticated/admin.new-repair'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin.payments'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin.products'
import { Route as AuthenticatedAdminRepairServicesRouteImport } from './routes/_authenticated/admin.repair-services'
import { Route as AuthenticatedAdminRepairsRouteImport } from './routes/_authenticated/admin.repairs'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminSellPhoneRouteImport } from './routes/_authenticated/admin.sell-phone'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminStaffRouteImport } from './routes/_authenticated/admin.staff'
import { Route as AuthenticatedAdminStockRouteImport } from './routes/_authenticated/admin.stock'
import { Route as AuthenticatedAdminSuppliersRouteImport } from './routes/_authenticated/admin.suppliers'
import { Route as AuthenticatedAdminWebsiteRouteImport } from './routes/_authenticated/admin.website'
import { Route as AuthenticatedAdminInvoicesIndexRouteImport } from './routes/_authenticated/admin.invoices.index'
import { Route as AuthenticatedAdminInvoicesInvoiceIdRouteImport } from './routes/_authenticated/admin.invoices.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PhoneRepairOrmskirkRoute = PhoneRepairOrmskirkRouteImport.update({
  id: '/phone-repair-ormskirk',
  path: '/phone-repair-ormskirk',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RepairsRoute = RepairsRouteImport.update({
  id: '/repairs',
  path: '/repairs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourPhoneRoute = SellYourPhoneRouteImport.update({
  id: '/sell-your-phone',
  path: '/sell-your-phone',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockingRoute = UnlockingRouteImport.update({
  id: '/unlocking',
  path: '/unlocking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBuyPhoneRoute =
  AuthenticatedAdminBuyPhoneRouteImport.update({
    id: '/buy-phone',
    path: '/buy-phone',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDayEndRoute =
  AuthenticatedAdminDayEndRouteImport.update({
    id: '/day-end',
    path: '/day-end',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDirectSaleRoute =
  AuthenticatedAdminDirectSaleRouteImport.update({
    id: '/direct-sale',
    path: '/direct-sale',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEnquiriesRoute =
  AuthenticatedAdminEnquiriesRouteImport.update({
    id: '/enquiries',
    path: '/enquiries',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoiceTermsRoute =
  AuthenticatedAdminInvoiceTermsRouteImport.update({
    id: '/invoice-terms',
    path: '/invoice-terms',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNewRepairRoute =
  AuthenticatedAdminNewRepairRouteImport.update({
    id: '/new-repair',
    path: '/new-repair',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRepairServicesRoute =
  AuthenticatedAdminRepairServicesRouteImport.update({
    id: '/repair-services',
    path: '/repair-services',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRepairsRoute =
  AuthenticatedAdminRepairsRouteImport.update({
    id: '/repairs',
    path: '/repairs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSellPhoneRoute =
  AuthenticatedAdminSellPhoneRouteImport.update({
    id: '/sell-phone',
    path: '/sell-phone',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStaffRoute = AuthenticatedAdminStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminStockRoute = AuthenticatedAdminStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSuppliersRoute =
  AuthenticatedAdminSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminWebsiteRoute =
  AuthenticatedAdminWebsiteRouteImport.update({
    id: '/website',
    path: '/website',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesIndexRoute =
  AuthenticatedAdminInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesInvoiceIdRoute =
  AuthenticatedAdminInvoicesInvoiceIdRouteImport.update({
    id: '/invoices/$invoiceId',
    path: '/invoices/$invoiceId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/phone-repair-ormskirk': typeof PhoneRepairOrmskirkRoute
  '/privacy': typeof PrivacyRoute
  '/repairs': typeof RepairsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sell': typeof SellRoute
  '/sell-your-phone': typeof SellYourPhoneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlocking': typeof UnlockingRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/admin/buy-phone': typeof AuthenticatedAdminBuyPhoneRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/day-end': typeof AuthenticatedAdminDayEndRoute
  '/admin/direct-sale': typeof AuthenticatedAdminDirectSaleRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/invoice-terms': typeof AuthenticatedAdminInvoiceTermsRoute
  '/admin/new-repair': typeof AuthenticatedAdminNewRepairRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/repair-services': typeof AuthenticatedAdminRepairServicesRoute
  '/admin/repairs': typeof AuthenticatedAdminRepairsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sell-phone': typeof AuthenticatedAdminSellPhoneRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/admin/invoices/': typeof AuthenticatedAdminInvoicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/phone-repair-ormskirk': typeof PhoneRepairOrmskirkRoute
  '/privacy': typeof PrivacyRoute
  '/repairs': typeof RepairsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sell': typeof SellRoute
  '/sell-your-phone': typeof SellYourPhoneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlocking': typeof UnlockingRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/shop': typeof ShopIndexRoute
  '/admin/buy-phone': typeof AuthenticatedAdminBuyPhoneRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/day-end': typeof AuthenticatedAdminDayEndRoute
  '/admin/direct-sale': typeof AuthenticatedAdminDirectSaleRoute
  '/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/admin/invoice-terms': typeof AuthenticatedAdminInvoiceTermsRoute
  '/admin/new-repair': typeof AuthenticatedAdminNewRepairRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/repair-services': typeof AuthenticatedAdminRepairServicesRoute
  '/admin/repairs': typeof AuthenticatedAdminRepairsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sell-phone': typeof AuthenticatedAdminSellPhoneRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/admin/stock': typeof AuthenticatedAdminStockRoute
  '/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/phone-repair-ormskirk': typeof PhoneRepairOrmskirkRoute
  '/privacy': typeof PrivacyRoute
  '/repairs': typeof RepairsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/reviews': typeof ReviewsRoute
  '/sell': typeof SellRoute
  '/sell-your-phone': typeof SellYourPhoneRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/unlocking': typeof UnlockingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/shop/$slug': typeof ShopSlugRoute
  '/shop/': typeof ShopIndexRoute
  '/_authenticated/admin/buy-phone': typeof AuthenticatedAdminBuyPhoneRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/day-end': typeof AuthenticatedAdminDayEndRoute
  '/_authenticated/admin/direct-sale': typeof AuthenticatedAdminDirectSaleRoute
  '/_authenticated/admin/enquiries': typeof AuthenticatedAdminEnquiriesRoute
  '/_authenticated/admin/invoice-terms': typeof AuthenticatedAdminInvoiceTermsRoute
  '/_authenticated/admin/new-repair': typeof AuthenticatedAdminNewRepairRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/repair-services': typeof AuthenticatedAdminRepairServicesRoute
  '/_authenticated/admin/repairs': typeof AuthenticatedAdminRepairsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sell-phone': typeof AuthenticatedAdminSellPhoneRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/staff': typeof AuthenticatedAdminStaffRoute
  '/_authenticated/admin/stock': typeof AuthenticatedAdminStockRoute
  '/_authenticated/admin/suppliers': typeof AuthenticatedAdminSuppliersRoute
  '/_authenticated/admin/website': typeof AuthenticatedAdminWebsiteRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/invoices/$invoiceId': typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  '/_authenticated/admin/invoices/': typeof AuthenticatedAdminInvoicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/phone-repair-ormskirk'
    | '/privacy'
    | '/repairs'
    | '/reset-password'
    | '/reviews'
    | '/sell'
    | '/sell-your-phone'
    | '/sitemap.xml'
    | '/terms'
    | '/unlocking'
    | '/admin'
    | '/shop/$slug'
    | '/shop/'
    | '/admin/buy-phone'
    | '/admin/customers'
    | '/admin/day-end'
    | '/admin/direct-sale'
    | '/admin/enquiries'
    | '/admin/invoice-terms'
    | '/admin/new-repair'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/repair-services'
    | '/admin/repairs'
    | '/admin/reports'
    | '/admin/sell-phone'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/stock'
    | '/admin/suppliers'
    | '/admin/website'
    | '/admin/'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/phone-repair-ormskirk'
    | '/privacy'
    | '/repairs'
    | '/reset-password'
    | '/reviews'
    | '/sell'
    | '/sell-your-phone'
    | '/sitemap.xml'
    | '/terms'
    | '/unlocking'
    | '/shop/$slug'
    | '/shop'
    | '/admin/buy-phone'
    | '/admin/customers'
    | '/admin/day-end'
    | '/admin/direct-sale'
    | '/admin/enquiries'
    | '/admin/invoice-terms'
    | '/admin/new-repair'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/repair-services'
    | '/admin/repairs'
    | '/admin/reports'
    | '/admin/sell-phone'
    | '/admin/settings'
    | '/admin/staff'
    | '/admin/stock'
    | '/admin/suppliers'
    | '/admin/website'
    | '/admin'
    | '/admin/invoices/$invoiceId'
    | '/admin/invoices'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/phone-repair-ormskirk'
    | '/privacy'
    | '/repairs'
    | '/reset-password'
    | '/reviews'
    | '/sell'
    | '/sell-your-phone'
    | '/sitemap.xml'
    | '/terms'
    | '/unlocking'
    | '/_authenticated/admin'
    | '/shop/$slug'
    | '/shop/'
    | '/_authenticated/admin/buy-phone'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/day-end'
    | '/_authenticated/admin/direct-sale'
    | '/_authenticated/admin/enquiries'
    | '/_authenticated/admin/invoice-terms'
    | '/_authenticated/admin/new-repair'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/repair-services'
    | '/_authenticated/admin/repairs'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sell-phone'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/staff'
    | '/_authenticated/admin/stock'
    | '/_authenticated/admin/suppliers'
    | '/_authenticated/admin/website'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/invoices/$invoiceId'
    | '/_authenticated/admin/invoices/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PhoneRepairOrmskirkRoute: typeof PhoneRepairOrmskirkRoute
  PrivacyRoute: typeof PrivacyRoute
  RepairsRoute: typeof RepairsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ReviewsRoute: typeof ReviewsRoute
  SellRoute: typeof SellRoute
  SellYourPhoneRoute: typeof SellYourPhoneRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  UnlockingRoute: typeof UnlockingRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phone-repair-ormskirk': {
      id: '/phone-repair-ormskirk'
      path: '/phone-repair-ormskirk'
      fullPath: '/phone-repair-ormskirk'
      preLoaderRoute: typeof PhoneRepairOrmskirkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repairs': {
      id: '/repairs'
      path: '/repairs'
      fullPath: '/repairs'
      preLoaderRoute: typeof RepairsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-phone': {
      id: '/sell-your-phone'
      path: '/sell-your-phone'
      fullPath: '/sell-your-phone'
      preLoaderRoute: typeof SellYourPhoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlocking': {
      id: '/unlocking'
      path: '/unlocking'
      fullPath: '/unlocking'
      preLoaderRoute: typeof UnlockingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/buy-phone': {
      id: '/_authenticated/admin/buy-phone'
      path: '/buy-phone'
      fullPath: '/admin/buy-phone'
      preLoaderRoute: typeof AuthenticatedAdminBuyPhoneRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/day-end': {
      id: '/_authenticated/admin/day-end'
      path: '/day-end'
      fullPath: '/admin/day-end'
      preLoaderRoute: typeof AuthenticatedAdminDayEndRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/direct-sale': {
      id: '/_authenticated/admin/direct-sale'
      path: '/direct-sale'
      fullPath: '/admin/direct-sale'
      preLoaderRoute: typeof AuthenticatedAdminDirectSaleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/enquiries': {
      id: '/_authenticated/admin/enquiries'
      path: '/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AuthenticatedAdminEnquiriesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoice-terms': {
      id: '/_authenticated/admin/invoice-terms'
      path: '/invoice-terms'
      fullPath: '/admin/invoice-terms'
      preLoaderRoute: typeof AuthenticatedAdminInvoiceTermsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/new-repair': {
      id: '/_authenticated/admin/new-repair'
      path: '/new-repair'
      fullPath: '/admin/new-repair'
      preLoaderRoute: typeof AuthenticatedAdminNewRepairRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/repair-services': {
      id: '/_authenticated/admin/repair-services'
      path: '/repair-services'
      fullPath: '/admin/repair-services'
      preLoaderRoute: typeof AuthenticatedAdminRepairServicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/repairs': {
      id: '/_authenticated/admin/repairs'
      path: '/repairs'
      fullPath: '/admin/repairs'
      preLoaderRoute: typeof AuthenticatedAdminRepairsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sell-phone': {
      id: '/_authenticated/admin/sell-phone'
      path: '/sell-phone'
      fullPath: '/admin/sell-phone'
      preLoaderRoute: typeof AuthenticatedAdminSellPhoneRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/staff': {
      id: '/_authenticated/admin/staff'
      path: '/staff'
      fullPath: '/admin/staff'
      preLoaderRoute: typeof AuthenticatedAdminStaffRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/stock': {
      id: '/_authenticated/admin/stock'
      path: '/stock'
      fullPath: '/admin/stock'
      preLoaderRoute: typeof AuthenticatedAdminStockRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/suppliers': {
      id: '/_authenticated/admin/suppliers'
      path: '/suppliers'
      fullPath: '/admin/suppliers'
      preLoaderRoute: typeof AuthenticatedAdminSuppliersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/website': {
      id: '/_authenticated/admin/website'
      path: '/website'
      fullPath: '/admin/website'
      preLoaderRoute: typeof AuthenticatedAdminWebsiteRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices/': {
      id: '/_authenticated/admin/invoices/'
      path: '/invoices'
      fullPath: '/admin/invoices/'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices/$invoiceId': {
      id: '/_authenticated/admin/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/admin/invoices/$invoiceId'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBuyPhoneRoute: typeof AuthenticatedAdminBuyPhoneRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminDayEndRoute: typeof AuthenticatedAdminDayEndRoute
  AuthenticatedAdminDirectSaleRoute: typeof AuthenticatedAdminDirectSaleRoute
  AuthenticatedAdminEnquiriesRoute: typeof AuthenticatedAdminEnquiriesRoute
  AuthenticatedAdminInvoiceTermsRoute: typeof AuthenticatedAdminInvoiceTermsRoute
  AuthenticatedAdminNewRepairRoute: typeof AuthenticatedAdminNewRepairRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminRepairServicesRoute: typeof AuthenticatedAdminRepairServicesRoute
  AuthenticatedAdminRepairsRoute: typeof AuthenticatedAdminRepairsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSellPhoneRoute: typeof AuthenticatedAdminSellPhoneRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminStaffRoute: typeof AuthenticatedAdminStaffRoute
  AuthenticatedAdminStockRoute: typeof AuthenticatedAdminStockRoute
  AuthenticatedAdminSuppliersRoute: typeof AuthenticatedAdminSuppliersRoute
  AuthenticatedAdminWebsiteRoute: typeof AuthenticatedAdminWebsiteRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminInvoicesInvoiceIdRoute: typeof AuthenticatedAdminInvoicesInvoiceIdRoute
  AuthenticatedAdminInvoicesIndexRoute: typeof AuthenticatedAdminInvoicesIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBuyPhoneRoute: AuthenticatedAdminBuyPhoneRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminDayEndRoute: AuthenticatedAdminDayEndRoute,
  AuthenticatedAdminDirectSaleRoute: AuthenticatedAdminDirectSaleRoute,
  AuthenticatedAdminEnquiriesRoute: AuthenticatedAdminEnquiriesRoute,
  AuthenticatedAdminInvoiceTermsRoute: AuthenticatedAdminInvoiceTermsRoute,
  AuthenticatedAdminNewRepairRoute: AuthenticatedAdminNewRepairRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminRepairServicesRoute: AuthenticatedAdminRepairServicesRoute,
  AuthenticatedAdminRepairsRoute: AuthenticatedAdminRepairsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSellPhoneRoute: AuthenticatedAdminSellPhoneRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminStaffRoute: AuthenticatedAdminStaffRoute,
  AuthenticatedAdminStockRoute: AuthenticatedAdminStockRoute,
  AuthenticatedAdminSuppliersRoute: AuthenticatedAdminSuppliersRoute,
  AuthenticatedAdminWebsiteRoute: AuthenticatedAdminWebsiteRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminInvoicesInvoiceIdRoute:
    AuthenticatedAdminInvoicesInvoiceIdRoute,
  AuthenticatedAdminInvoicesIndexRoute: AuthenticatedAdminInvoicesIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PhoneRepairOrmskirkRoute: PhoneRepairOrmskirkRoute,
  PrivacyRoute: PrivacyRoute,
  RepairsRoute: RepairsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ReviewsRoute: ReviewsRoute,
  SellRoute: SellRoute,
  SellYourPhoneRoute: SellYourPhoneRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  UnlockingRoute: UnlockingRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
